version: '3'
services:
  eve:
    build: .
    image: mike/eve:1.0
    ports:
      - "5000:5000"
#    volumes:
#      - ./eveconfig:/eveconfig
    environment:
      EVE_ENV: development
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"